language: node_js
node_js:
  - 8.5.0
before_script: cd server
script:
  - "npm install"
  - "npm run lint"
  - "npm run test"
deploy:
  provider: heroku
  api_key: 452d90d0-cd5c-4d43-818a-ab045e327d60
  app: basav-nodejs-weatherapp
  on: master
