version: '3'

services:
  weatherapp:
    image: weatherapp:0.1.0
    build: .
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 256M
      restart_policy:
        condition: any
    ports:
      - "3000:3000"
    env_file: "./dockerenv/docker_${NODE_ENV:-development}.env"
